### PR TITLE
style: remove unnecessary mut and unsafe keywords

### PR DESCRIPTION
**Pull request by oherrala**
Compiler nagged about these. Remove it to please the compiler.

### CODE REVIEW

**Comment by indiv0** [comment]
Apparently this changed in a recent compiler version, so the [Travis test](https://travis-ci.org/indiv0/lazycell/jobs/363080776) for rustc 1.13.0 is failing. Would you mind figuring out the minimum rustc version on which this PR will compile and update the [.travis.yml](https://github.com/indiv0/lazycell/blob/master/.travis.yml#L19) accordingly?

Also, please add yourself to [CONTRIBUTORS.md](https://github.com/indiv0/lazycell/blob/master/CONTRIBUTORS.md) in the PR.

**Comment by oherrala** [comment]
Sorry, I didn't get any message from Travis about the fail.

Apparently change required for this PR is released in Rust 1.25.0. Here are related issue and PR: https://github.com/rust-lang/rust/issues/35067 and https://github.com/rust-lang/rust/pull/47204.

This change is so minor that breaking compatibility with older Rust is not beneficial so this change could wait and instead add `#[allow(unused_unsafe)] unsafe { ... }` to remove the nag for newer compilers.

**Comment by indiv0** [comment]
Great! Looks good to me. Minor nitpicks though, would you mind amending the commits by adding `style:` and `chore:` prefixes to their messages and removing the capitalization on "Allow" and "Update" (just so that my changelog generator doesn't complain).

**Comment by oherrala** [comment]
Re-pushed changes with fixed commit messages.

**Comment by indiv0** [comment]
Awesome, thank you for the PR!

**Pull request merged**
