### PR TITLE
Derive Debug impls

### PR DESCRIPTION
**Pull request by oconnor663**

### CODE REVIEW

**Comment by indiv0** [comment]
Looks like `derive` isn't implemented for `UnsafeCell` in 1.8.0. I'll just have to bump the minimum rustc version checked in Travis prior to merging this.

**Comment by indiv0** [comment]
Also, could you please re-title the commit to be `impr: derive Debug impls`?

**Comment by indiv0** [comment]
Sorry, not rename the issue but the commit itself :P

**Comment by oconnor663** [comment]
Thanks for the quick followup. Rebased to get a new CI run with your version bump.

Edit: woops, thanks for taking care of the commit name

**Comment by indiv0** [comment]
Sounds good! Just rename the commit and it's good to go.

**Comment by indiv0** [comment]
Merged in https://github.com/indiv0/lazycell/commit/9da0a5a2ffac1fef03ef02851c2c89d26d67d225. Thanks!

**Comment by indiv0** [comment]
I've released v0.5.1 ([crates.io](https://crates.io/crates/lazycell/0.5.1), [github](https://github.com/indiv0/lazycell/releases/tag/v0.5.1)) with this PR included.

**Comment by oconnor663** [comment]
Thanks!

**Pull request closed without merging**
