### PR TITLE
feat: add LazyCell::try_borrow_with

### PR DESCRIPTION
**Pull request by matklad**
Adds a convenient API for initialization of the cell with a function which can fail. Equivalent to the following code with unwrap:

```Rust
if let Some(value) = lazycell.borrow() {
    Ok(value)
} else {
    lazycell.fill(f()?);
    Ok(lazycell.borrow().unwrap())
}
```

We find this API rather useful in Cargo (under a different name): https://github.com/rust-lang/cargo/search?utf8=%E2%9C%93&q=get_or_try_init&type=

### CODE REVIEW

**Comment by indiv0** [comment]
I believe this function has the same soundness issues as the existing `borrow_mut` (see: #66), so I'd prefer to fix the existing one first, then merge this one (in a fixed form) as well.

**Comment by indiv0** [comment]
@matklad actually, I see that you already have a commit for the issue: https://github.com/indiv0/lazycell/commit/99df6e14edc0ec800cc09105b89b48dc57a6e77c. Any reason you haven't opened a PR for it? It looks good to me.

**Comment by matklad** [comment]
Yeah, I've now noticed that I have that fix too :) No idea why I haven't open a PR, just a sec!

**Comment by matklad** [comment]
closing in favor of https://github.com/indiv0/lazycell/pull/74

**Pull request closed without merging**
