### PR TITLE
docs: fix missing backticks

### PR DESCRIPTION
**Pull request by oconnor663**

### CODE REVIEW

**Comment by indiv0** [comment]
Thank you!

**Comment by indiv0** [comment]
Actually I should've probably mentioned this (I think it's missing from the `CONTRIBUTING.md`), but any contribution warrants being added to the `CONTRIBUTORS.md`. I can handle it for you, if you'd like.

(I'll have to update the copyright date to `2016-2017` anyways so it's not a problem)

**Comment by oconnor663** [comment]
Ha sounds good. Maybe you can put my name in an extremely tiny font :)

**Comment by oconnor663** [comment]
Also btw this crate solves a really important problem very cleanly, and I'm shocked it doesn't have more stars.

**Comment by indiv0** [comment]
🤷‍ discoverability is hard.

**Pull request merged**
