### PR TITLE
Add `LazyCell::replace` for infallible access

### PR DESCRIPTION
**Pull request by alexcrichton**
This differs from other functions that it requires `&mut self` but if you've
locally got access to `&mut self` in code it's often quite handy to take
advantage of such privileged access!

### CODE REVIEW

**Comment by alexcrichton** [comment]
ping @indiv0, was curious if you'd have a chance to take a look at this?

**Comment by indiv0** [comment]
Hello! Sorry I haven't had a chance to take a look at this yet. I'll take a look first thing tomorrow.

**Comment by indiv0** [comment]
Looks good to me, merged! Thanks for the contribution. I'll publish a new version to crates.io now.

**Comment by alexcrichton** [comment]
Awesome, thanks so much!

**Pull request merged**
