### PR TITLE
Add `LazyCell::borrow_mut_with` and `LazyCell::try_borrow_mut_with`.

### LINKED ISSUE #79: LazyCell::borrow_mut_with
Since commit fd419dea965ff1ad3853f26f37e8d107c6ca096c added `borrow_mut` to `LazyCell`, would it also make sense to add `borrow_mut_with`? That seems like the most useful abstraction for using a LazyCell mutably. But maybe there's a subtle soundness issue I'm not thinking of?

### LINKED ISSUE #80: LazyCell::try_borrow_mut_with
Similar to #79, should `LazyCell` have a `try_borrow_mut_with` method as well?

### PR DESCRIPTION
**Pull request by dherman**
- Closes #79.
- Closes #80.

Again, this was my best guess but I'm not entirely confident of what I'm doing. :)

### CODE REVIEW

**Comment by matklad** [comment]
@dherman do you have particular use-cases for this functions, or are they added just for the sake of orthogonality? 

I believe that the main motivation for `borrow_mut` was that you can't achieve it's functionality using only the public API. That is, `borrow_mut` is not a convenience function but an empowering function. 

And looks like `borrow_mut_with` and `try_borrow_mut_with` could be implemented externally?

**Comment by indiv0** [comment]
@dherman I have the same question as matklad. I'm not categorically opposed to adding these functions, but I'd prefer to do so only in the event that someone actually has an existing, demonstrable use-case for them. This is primarily to avoid unnecessary expansion of the API surface.

And yeah, it looks like these could be implemented externally, so I'm not sure they necessary belong in the library itself.

**Comment by indiv0** [comment]
@dherman I have the same question as matklad. I'm not categorically opposed to adding these functions, but I'd prefer to do so only in the event that someone actually has an existing, demonstrable use-case for them. This is primarily to avoid unnecessary expansion of the API surface.

And yeah, it looks like these could be implemented externally, so I'm not sure they necessary belong in the library itself.

(That said, your PRs look good from a code & documentation standpoint).

**Comment by withoutboats** [comment]
I needed this functionality today & I found it frustrating and surprising that they did not exist. I specifically needed `try_borrow_mut_with`, which is not trivial to implement myself. I can implement both `borrow_with` and `try_borrow_with` externally also, but they are valuable convenience APIs & I see no reason to favor the immutable versions over the mutable versions.

**Comment by dherman** [comment]
D'oh, I forgot to keep on top of these PR threads!

> @dherman do you have particular use-cases for this functions, or are they added just for the sake of orthogonality?

There are instances of both `try_borrow_with` and `try_borrow_mut_with` in my [Notion project](https://github.com/notion-cli/notion), which uses LazyCell pretty prevalently.

> I'd prefer to do so only in the event that someone actually has an existing, demonstrable use-case for them. This is primarily to avoid unnecessary expansion of the API surface.

In my experience the `with` functions are representative of the most common pattern for lazy initialization. It's rare that I want to ask for a lazily initialized value and just get no value if it's not yet initialized. When I'm using a lazy cell, I want it to be morally equivalent to eager initialization, but performed just-in-time. Which means that when I query the value, I always want to get a value; I just need to specify how to initialize it just-in-time.

The point of LazyCell is to abstract away these common patterns—as you can see in the PR, it's a nontrivial amount of boilerplate. I'd prefer to see the API surface grow a little to avoid diffusion of responsibility and lots of copied boilerplate in downstream codebases.

> And yeah, it looks like these could be implemented externally, so I'm not sure they necessary belong in the library itself.

In practice, this would mean that I would need to create a LazyCellExt crate with a LazyCellExt trait that implements these methods, and then add an extra crate to my dependencies and import the trait anywhere I wanted these methods. That seems like a bit worse user experience, and from the user's perspective, there's no savings in API surface.

**Comment by indiv0** [comment]
@dherman sorry for the late reply. I've been away on vacation.

I agree with your reasoning. I'll be accepting your PR (I'll try to get it done over this weekend).

**Comment by indiv0** [comment]
Closed by fdc6d268f0e9a6668768302f45fe2bb4aa9a7c34.

Thank you for your PRs @dherman.
I'll be publishing a new version of the crate shortly.

**Comment by indiv0** [comment]
v1.1.0, which incorporates these PRs, has now been published.

**Pull request closed without merging**
