### PR TITLE
Fix a soundness hole

### PR DESCRIPTION
**Pull request by matklad**

### CODE REVIEW

**Comment by matklad** [comment]
Hm, this fails on Rust 1.9.0. Would you mind bumping the minimal supported version of Rust?

**Comment by indiv0** [comment]
Yep, already on it: #75 :)

**Comment by indiv0** [comment]
Would you mind rebasing this on master, as one of the commits was already merged in a previous PR?

**Comment by indiv0** [comment]
Also, feel free to add a commit adding yourself to the CONTRIBUTORS.md file!

**Comment by matklad** [comment]
Yeah, I'll do this as soon as I get home (couple of hours) :)

**Comment by matklad** [comment]
rebased

This also includes `try_borrow_with` from #73

**Comment by indiv0** [comment]
Merged, thank you! If you can think of any other PRs to bring the API more in-line with what Cargo's LazyCell does, I'd be glad to receive them.

I'll publish a new version of the library soon.

**Pull request merged**
